//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BD_RumboAgilEntities : DbContext
    {
        public BD_RumboAgilEntities()
            : base("name=BD_RumboAgilEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<T_Estado> T_Estado { get; set; }
        public virtual DbSet<T_Evento> T_Evento { get; set; }
        public virtual DbSet<T_Lider> T_Lider { get; set; }
        public virtual DbSet<T_Lider_Ministerio> T_Lider_Ministerio { get; set; }
        public virtual DbSet<T_Lugar> T_Lugar { get; set; }
        public virtual DbSet<T_Miembro> T_Miembro { get; set; }
        public virtual DbSet<T_Miembro_Ministerio> T_Miembro_Ministerio { get; set; }
        public virtual DbSet<T_Ministerio> T_Ministerio { get; set; }
        public virtual DbSet<T_Operacion> T_Operacion { get; set; }
        public virtual DbSet<T_Participante> T_Participante { get; set; }
        public virtual DbSet<T_Persona> T_Persona { get; set; }
        public virtual DbSet<T_TipoEvento> T_TipoEvento { get; set; }
        public virtual DbSet<T_Usuario> T_Usuario { get; set; }
    }
}
