//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Evento
    {
        public T_Evento()
        {
            this.T_Operacion = new HashSet<T_Operacion>();
            this.T_Participante = new HashSet<T_Participante>();
        }
    
        public short Id_Evento { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime Fecha_Inicio { get; set; }
        public Nullable<System.TimeSpan> Hora_Inicio { get; set; }
        public System.DateTime Fecha_fin { get; set; }
        public Nullable<System.TimeSpan> Hora_fin { get; set; }
        public string Comentario { get; set; }
        public byte Id_Estado { get; set; }
        public byte Id_TipoEvento { get; set; }
        public byte Id_Lugar { get; set; }
        public short Id_Lider { get; set; }
        public Nullable<int> NumeroEvento { get; set; }
    
        public virtual T_Estado T_Estado { get; set; }
        public virtual T_Lider T_Lider { get; set; }
        public virtual T_Lugar T_Lugar { get; set; }
        public virtual T_TipoEvento T_TipoEvento { get; set; }
        public virtual ICollection<T_Operacion> T_Operacion { get; set; }
        public virtual ICollection<T_Participante> T_Participante { get; set; }
    }
}
