//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Lider
    {
        public T_Lider()
        {
            this.T_Evento = new HashSet<T_Evento>();
            this.T_Lider_Ministerio = new HashSet<T_Lider_Ministerio>();
        }
    
        public short Id_Lider { get; set; }
        public bool EnActividad { get; set; }
        public string Llamado { get; set; }
    
        public virtual ICollection<T_Evento> T_Evento { get; set; }
        public virtual T_Persona T_Persona { get; set; }
        public virtual ICollection<T_Lider_Ministerio> T_Lider_Ministerio { get; set; }
    }
}
