//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Lider_Ministerio
    {
        public byte Id_Ministerio { get; set; }
        public short Id_Lider { get; set; }
        public System.DateTime FechaAsignacion { get; set; }
    
        public virtual T_Lider T_Lider { get; set; }
        public virtual T_Ministerio T_Ministerio { get; set; }
    }
}
