//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Miembro
    {
        public T_Miembro()
        {
            this.T_Miembro_Ministerio = new HashSet<T_Miembro_Ministerio>();
        }
    
        public short Id_Miembro { get; set; }
        public string TipoMiembro { get; set; }
    
        public virtual T_Persona T_Persona { get; set; }
        public virtual ICollection<T_Miembro_Ministerio> T_Miembro_Ministerio { get; set; }
    }
}
