//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Usuario
    {
        public T_Usuario()
        {
            this.T_Operacion = new HashSet<T_Operacion>();
        }
    
        public short Id_Usuario { get; set; }
        public string Email { get; set; }
        public string Clave { get; set; }
    
        public virtual ICollection<T_Operacion> T_Operacion { get; set; }
        public virtual T_Persona T_Persona { get; set; }
    }
}
